"""banners and banner types

Revision ID: 8e454cf64a6d
Revises: 72f8d1695bdc
Create Date: 2021-05-04 13:35:55.526346

"""
from alembic import op
import sqlalchemy as sa
import gino.dialects.asyncpg

# revision identifiers, used by Alembic.
revision = '8e454cf64a6d'
down_revision = '72f8d1695bdc'
branch_labels = None
depends_on = None


banner_statuses = gino.dialects.asyncpg.AsyncEnum(
    'NOT_STARTED', 'IN_PROGRESS', 'CANCELLED', 'DONE', name='bannerstatus'
)
primary_banner_types = gino.dialects.asyncpg.AsyncEnum(
    'HUMAN', 'STATIC', name='primarybannertype'
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'banner_types',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('primary_type', primary_banner_types, nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.create_table(
        'banners',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('cost', sa.Float(), nullable=False),
        sa.Column('start_date', sa.Date(), nullable=False),
        sa.Column('end_date', sa.Date(), nullable=False),
        sa.Column('address', sa.String(length=200), nullable=False),
        sa.Column('coordinates', sa.String(length=21), nullable=False),
        sa.Column('status', banner_statuses, nullable=False),
        sa.Column('advertising_company_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('banner_type_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            tuple(['advertising_company_id']), ['advertising_companies.id'],
        ),
        sa.ForeignKeyConstraint(
            tuple(['banner_type_id']), ['banner_types.id'],
        ),
        sa.ForeignKeyConstraint(tuple(['user_id']), ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('banners')
    op.drop_table('banner_types')
    banner_statuses.drop(op.get_bind())
    primary_banner_types.drop(op.get_bind())
    # ### end Alembic commands ###
